### ISSUE TITLE
onActivityResumed的时候，不重新hookView

### ISSUE THREAD

**Issue by lijianyou-Herve** [liys666666/DoubleClick#1]
很好的做法。但是建议onActivityResumed的时候，增加一个判断。已经hook过了，就不要再次的hookView。要不然每次pause,返回，全部重新hook，遍历所i有View+反射代理太消耗性能，且不必要。

**Comment by liys666666** [comment]
感谢反馈与支持，下个版本会修复这个问题的。


---原始邮件---
发件人: "lijianyou-Herve"<notifications@github.com>
发送时间: 2019年8月24日(星期六) 下午2:23
收件人: "liys666666/DoubleClick"<DoubleClick@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [liys666666/DoubleClick] onActivityResumed的时候，不重新hookView (#1)



很好的做法。但是建议onActivityResumed的时候，增加一个判断。已经hook过了，就不要再次的hookView。要不然每次pause,返回，全部重新hook，遍历所i有View+反射代理太消耗性能，且不必要。
 
&mdash;

**Comment by liys666666** [comment]
V1.0.3版本已经修复好了，非常感谢您。


---原始邮件---
发件人: "lijianyou-Herve"<notifications@github.com>
发送时间: 2019年8月24日(星期六) 下午2:23
收件人: "liys666666/DoubleClick"<DoubleClick@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [liys666666/DoubleClick] onActivityResumed的时候，不重新hookView (#1)



很好的做法。但是建议onActivityResumed的时候，增加一个判断。已经hook过了，就不要再次的hookView。要不然每次pause,返回，全部重新hook，遍历所i有View+反射代理太消耗性能，且不必要。
 
&mdash;
