### ISSUE TITLE
二个疑问

### ISSUE THREAD

**Issue by huangjiaqiang** [liys666666/DoubleClick#12]
疑问1：为了这么一个功能每次都去遍历所有的View，是否会有一定的性能损耗
疑问2：onClickListener被替换可能会引起隐蔽的bug（使用者并不知道被替换了）

**Comment by liys666666** [comment]
感谢您提出的问题，3.0版本已经采用aop的方式处理


---原始邮件---
发件人: &quot;huang&quot;<notifications@github.com&gt;
发送时间: 2019年11月5日(星期二) 上午9:15
收件人: &quot;liys666666/DoubleClick&quot;<DoubleClick@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [liys666666/DoubleClick] 二个疑问 (#12)



疑问1：为了这么一个功能每次都去遍历所有的View，是否会有一定的性能损耗
 疑问2：onClickListener被替换可能会引起&#x9690;蔽的bug（使用者并不知道被替换了）
 
&mdash;
