### ISSUE TITLE
加入该项目的依赖,报错了

### ISSUE THREAD

**Issue by yp199618** [liys666666/DoubleClick#2]
```
No resource identifier found for attribute 'appComponentFactory' in package 'android'
```

**Comment by liys666666** [comment]
不知道你的appcompat是哪个版本的?可以参考一下这个：https://blog.csdn.net/zxccxzzxz/article/details/82986956，看一下是不是版本不兼容。 框架中的SDK是28，appcompat-v7:28.0.0。如果还有问题，把你的Sdk和appcompat版本号发过来， 我看一下。

**Comment by yp199618** [comment]
```
compileSdkVersion 27
implementation 'com.android.support:appcompat-v7:27.1.1'
```

**Comment by liys666666** [comment]
换到1.0.4版本， 看一下可以了吗？
implementation 'com.github.liys666666:DoubleClick:V1.0.4'

**Comment by yp199618** [comment]
好用啦,爱你呦,么么哒!,感谢大佬

**Comment by liys666666** [comment]
客气了，^_^


---原始邮件---
发件人: "杨鹏"<notifications@github.com>
发送时间: 2019年8月26日(星期一) 晚上6:34
收件人: "liys666666/DoubleClick"<DoubleClick@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"liys"<401654546@qq.com>;
主题: Re: [liys666666/DoubleClick] 加入该项目的依赖,报错了 (#2)



好用啦,爱你呦,么么哒!,感谢大佬
 
&mdash;
