### ISSUE TITLE
项目运行不起来,AS 4.0

### ISSUE THREAD

**Issue by lydlovezjr** [liys666666/DoubleClick#23]
Cannot cast object 'com.android.build.gradle.internal.pipeline.TransformTask$2$1@7d4a8d38' with class 'com.android.build.gradle.internal.pipeline.TransformTask$2$1' to class 'com.android.build.gradle.internal.pipeline.TransformTask'

**Comment by lydlovezjr** [comment]
升级到2.0.10版本
Cause: zip file is empty

**Comment by liweiGe** [comment]
> Cannot cast object 'com.android.build.gradle.internal.pipeline.TransformTask$2$1@7d4a8d38' with class 'com.android.build.gradle.internal.pipeline.TransformTask$2$1' to class 'com.android.build.gradle.internal.pipeline.TransformTask'

我也遇到这个问题了,应该是没有适配最新的gradle版本

**Comment by liweiGe** [comment]
> 升级到2.0.10版本
> Cause: zip file is empty

我解决了,在app的build.gradle中加入:
aspectjx{
    exclude 'com.google','com.squareup','com.alipay','org.apache'
}
