### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by Sunshine-Joex** [liys666666/DoubleClick#3]
老铁，华为手机，Android 9 API28，无效果

**Comment by liys666666** [comment]
收到,  有时间我去看一下哈.

**Comment by Sunshine-Joex** [comment]
好的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: liys <notifications@github.com>
发送时间: Friday, August 30, 2019 10:59:34 AM
收件人: liys666666/DoubleClick <DoubleClick@noreply.github.com>
抄送: 子陌 <liuyangqiao@outlook.com>; Author <author@noreply.github.com>
主题: Re: [liys666666/DoubleClick] 兼容性问题 (#3)


收到, 有时间我去看一下哈.

―

**Comment by liys666666** [comment]
问题已解决: 更新到V2.0.2就可以了，我这边测试是没问题了。
