### ISSUE TITLE
在自定义view 功能

### ISSUE THREAD

**Issue by zsj6102** [liys666666/DoubleClick#5]
自定义view没有作用

**Comment by liys666666** [comment]
对应的view, 需要在Activity的onResume前, 加载到Activity中才有效，如果是onResume后加入的view， 可以使用ViewDoubleHelper.hookView(view)处理， 如果需要处理的view比较多, 也可以使用ViewDoubleHelper.hookActivity()重新刷新整个Activity

**Comment by zsj6102** [comment]
你可以试下recyclerview，没有生效

**Comment by liys666666** [comment]
OK有空我去看看

**Comment by liys666666** [comment]
最新版本V2.0.4已经修复好了, 如果还发现有其它问题， 欢迎提出来，我这边会尽量完善的。

**Comment by zsj6102** [comment]
嗯辛苦了还不适合用在项目中
