### ISSUE TITLE
Fragment中无效啊

### ISSUE THREAD

**Issue by 211885646** [liys666666/DoubleClick#6]
我看了你的demo  你的Fragment的点击事件是交给Activity去处理了  但是实际项目中不可能这样处理的,我用你的demo的Fragment让点击事件自己处理就无法防止重复点击了 ,依然会产生多次点击,项目想法挺好的,期待作者更新

**Comment by liys666666** [comment]
感谢您的反馈， 最新版本V2.0.4已经修复好了, 如果还发现其它问题， 欢迎提出来，我这边会尽量完善的。
