### ISSUE TITLE
关于自定义点击View的一个不适用场景

### ISSUE THREAD

**Issue by 211885646** [liys666666/DoubleClick#7]
在组件化中库的初始化放在基类中-----但是此库的初始化才能定制需要控制的需要另外设置的View或者Activity,我现在遇到一个什么场景呢?如下
我在BaseModule中初始化此库   我还有个ChatModule(其中有个表情键盘)  表情键盘需要能重复快速点击,但是ChatModule依赖的BaseModule,BaseModule并没有依赖ChatModule,导致在BaseModule中无法找到我需要自定义的ViewId   ,我的想法是这个设置能否抽成独立的方法出来

**Comment by liys666666** [comment]
你的提议很好, 我会考虑在下一个版本加进去的
