### ISSUE TITLE
组件化项目中如何使用~

### ISSUE THREAD

**Issue by 211885646** [liys666666/DoubleClick#8]
组件化项目中如何让子module中的控件或者页面单独排除呢

**Comment by liys666666** [comment]
可以在对应的Activity中手动调用ViewDoubleHelper.hookActivity(long delayTime); 参数传0就可以了.   或者ViewDoubleHelper.hookView(long delayTime)  单独View处理.   如果页面不多的话就暂时先用这两个方法,  下个版本会考虑你的意见, 把设置单独抽取成一个方法.

**Comment by 211885646** [comment]
原来有2个这么好的方法  文档中没发现 哈哈,但是我试了这个ViewDoubleHelper.hookView(view,0),发现快速点击会有顿挫感,并不是完全没有仿重复点击,我测试的是快速点击RecyclerView的item,设置了0以后  会有顿挫感  可以和原生的对比下

**Comment by liys666666** [comment]
hookView暂时先不建议用吧，我也是刚刚发现这个问题，兄弟，谢谢你提出的建议哈，下个版本这个问题会一起修复的。


---原始邮件---
发件人: &quot;211885646&quot;<notifications@github.com&gt;
发送时间: 2019年9月22日(星期日) 晚上10:26
收件人: &quot;liys666666/DoubleClick&quot;<DoubleClick@noreply.github.com&gt;;
抄送: &quot;Comment&quot;<comment@noreply.github.com&gt;;&quot;liys&quot;<401654546@qq.com&gt;;
主题: Re: [liys666666/DoubleClick] 组件化项目中如何使用~ (#8)



原来有2个这么好的方法  文档中没发现 &#x54C8;&#x54C8;,但是我试了这个ViewDoubleHelper.hookView(view,0),发现快速点击会有顿挫感,并不是完全没有仿重复点击,我测试的是快速点击RecyclerView的item,设置了0以后  会有顿挫感  可以和原生的对比下
 
&mdash;

**Comment by liys666666** [comment]
V2.0.5新版本刚刚发布了,  新增方法: ViewDoubleHelper.addAnnotationClass(annotationClass);  //可以设置多个, 在什么地方设置都可以.
