### ISSUE TITLE
关于需要重复点击(快速点击)

### ISSUE THREAD

**Issue by 211885646** [liys666666/DoubleClick#9]
首先很感谢作者大大,每天那么晚还在维护项目,之前有提到的去掉个别指定View或者Activity的重复点击,目前使用ViewDoubleHelper.hookChildViews(View view, long delayTime); 方法,delayTime设置0或者1否无法实现控件原生的快速点击,希望作者大大有空可以完善,这我边现在也在极力推广身边的小伙伴在使用这个库,想请作者大大喝咖啡  哈哈

**Comment by liys666666** [comment]
谢谢你的支持哈，兄弟，最新版本2.0.6已经修复了这个问题。


---原始邮件---
发件人: &quot;211885646&quot;<notifications@github.com&gt;
发送时间: 2019年9月24日(星期二) 晚上10:15
收件人: &quot;liys666666/DoubleClick&quot;<DoubleClick@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [liys666666/DoubleClick] 关于需要重复点击(快速点击) (#9)



首先很感谢作者大大,每天那么晚还在维护项目,之前有提到的去掉个别指定View或者Activity的重复点击,目前使用ViewDoubleHelper.hookChildViews(View view, long delayTime); 方法,delayTime设置0或者1否无法实现控&#x4EF6;原生的快速点击,希望作者大大有空可以完善,这我边现在也在极力推广身边的小伙伴在使用这个库,想请作者大大喝咖啡  &#x54C8;&#x54C8;
 
&mdash;

**Comment by 211885646** [comment]
作者大大,这个问题并没有被修复诶,经过我测试ViewDoubleHelper.hookActivity(0);是可以的,ViewDoubleHelper.hookChildViews(RecyclerView,0);还是和上个版本一样的问题~~不能快速重复点击,会顿一下,何以分别设置这个两个方法对比测试,我的RecyclerView的item点击事件是用的BaseRecyclerViewAdapterHelper这个库的点击事件,看源码应该是item的父布局产生的点击事件~
